# Generated by Django 6.0 on 2025-12-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
