# Generated by Django 6.0 on 2026-01-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_otp_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
