# Generated by Django 6.0 on 2026-01-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_is_2fa_enabled_user_last_otp_verified_at"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emailotp",
            name="users_email_user_id_f6f756_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailotp",
            name="users_email_expires_63503d_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_2fa_enabled",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_otp_verified_at",
        ),
        migrations.DeleteModel(
            name="EmailOTP",
        ),
    ]
