# Generated by Django 6.0 on 2026-01-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_userprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_moods',
            field=models.JSONField(blank=True, default=None, help_text='Array of preferred mood emojis. If empty or null, all moods are preferred.', null=True),
        ),
    ]
