# Generated by Django 6.0 on 2026-01-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoodTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color code for the tag (e.g., #6366f1)",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mood Tag",
                "verbose_name_plural": "Mood Tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="mood",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags associated with this mood",
                related_name="moods",
                to="moods.moodtag",
            ),
        ),
    ]
